name: Continous Integration
on:
  pull_request:
    branches: [ main ]
jobs:
  Style:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run : npm run lint:test
      - name: Check Branch Name
        run: npm run branch $GITHUB_HEAD_REF
  Unit_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Check Unit Tests
        run: npm test
