name: Pomo-App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Check_Styles:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run : npm run lint
