name: Pomo-App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  styleCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Check Unit Tests
        run: npm test
      - name: Lint
        run : npm run lint 
        
        
