# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Minify Files
        uses: devatherock/minify-js@v1.0.2
        with:
          directory: 'js'
          add_suffix: false
      - name: Delete Uneccessary Files 
        run: rm -rf coverage/ && rm -rf docs/ && rm -rf tests/ 
      - name: Push changes 
        uses: actions-js/push@v1.2
        with:
          github_token: ${{secrets.API_TOKEN_GITHUB }}
          branch: 'production'
          force: true
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build Docs 
        run: npm run doc
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
         API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB }}
        with:
         source-directory: 'docs'
         destination-github-username: 'Anshul-Birla'
         destination-repository-name: 'PomoDoc'
         user-email: anbirla@ucsd.edu
        


      
      
          

